export const themeList = [
  { name: "light", color: "#ffffff" },
  { name: "dark", color: "#1d232a" },
  { name: "dracula", color: "#282a36" },
  { name: "synthwave", color: "#2d1b69" },
  { name: "cyberpunk", color: "#ff7598" },
  { name: "retro", color: "#e4d8b4" },
  { name: "forest", color: "#1b4332" },
  { name: "garden", color: "#2f855a" },
  { name: "aqua", color: "#06b6d4" },
  { name: "nord", color: "#3b4252" },
  { name: "luxury", color: "#09090b" },
  { name: "business", color: "#1f2937" },
  { name: "black", color: "#000000" },
  { name: "halloween", color: "#ff7f11" },
  { name: "valentine", color: "#e96d7b" },
  { name: "sunset", color: "#ff8c42" },
  { name: "coffee", color: "#4b2e2b" },
  { name: "bumblebee", color: "#facc15" },
  { name: "emerald", color: "#10b981" },
  { name: "acid", color: "#bfff00" },
];
